# Generated by Django 5.1.14 on 2025-11-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('fabricante', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=10)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='Examen.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=10)),
                ('ventas_estimadas', models.FloatField(max_length=10)),
                ('estudio_desarrollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='Examen.estudio')),
                ('plataforma', models.ManyToManyField(blank=True, related_name='videojuegos', to='Examen.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('puntuacion', models.FloatField(max_length=3)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='Examen.videojuego')),
            ],
        ),
    ]
