# Generated by Django 5.1.14 on 2025-11-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='critico',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
