# Generated by Django 5.1.14 on 2025-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_analisis_critico'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True),
        ),
    ]
